process-engine/process_engine_core

- package.json
Moment 2.19.0 doesn't play nice with webpack, so we pin it to 2.18.1. See https://github.com/moment/moment/issues/4228
> 📌 pin moment to 2.18.1 bc. moment#4228

- src/entity_types/process.ts
- src/entity_types/subprocess_external.ts
Handling of process token in external subprocesses changed.
**Former behavior**
The complete token data including current and history is passed to the subprocess and the subprocess is returning its complete token data including history.
**Current behavior**
Only the current token of the parent process is passed to the subprocess. The subprocess returns only its last current token.
> change token handling of subprocess

- src/entity_types/process_def.ts
Allow changing the processdef key using the bpmn diagram. Now when you call updateBpmn the processengine update the internal hold key of the process.
Try https://github.com/process-engine/charon/issues/31
> ✨ Allow changing the key of the processdef using the bpmn diagram

- src/entity_types/subprocess_external.ts
fixes https://github.com/process-engine/process_engine/issues/23
It also fixes the wrong usage of the forwarded context. The context of the initial caller should be used here.
Build a process with a call activity pointing to a process having a user task inside. Run the process with a client having a participantId. The user task within the call activity will now be delegated to correct participant channel.
> forward participant, fix usage of wrong context

- src/entity_types/user_task.ts
This fixes issue https://github.com/process-engine/process_engine/issues/37. See description there.
Execute a process containing user tasks and inspect much lower memory footprint.
> Process token growths too much, when user task is executed

- src/entity_types/user_task.ts
This fixes issue https://github.com/process-engine/process_engine/issues/34
Start a process with a lane where no role is attached. There should be an appropriate message on the participant channel.
> Participant ID is nulled, when the lane has no role attached

- package.json
- src/bpmn_diagram.ts
- src/process_engine_service.ts
I added a method that allows us to directly import BPMN diagrams.
This also fixes importing Models that have laneSets, but no lanes in them.
- The Processes imported through this method might not bexecutable!
- This should currently not be used to import models with more than one process, because of #54!
- Use this Version of process_engine and `^1.1.0` of process_engine_http in a process-engine
- `POST /processengine/create_bpmn_from_xml` with this body:
```
{
"xml": "YOUR_BPMN_XML_STRING"
}
```
- See how the processes of that model are now in the database
> ✨ add createBpmnFromXml

- src/entity_types/script_task.ts
Having an interrupting boundary event will indirectly cause the script task to 'end' if an error is thrown.
The script task also 'end's on its own in a regualar fashion
Both 'end' calls will cause a duplicate call to save. This race condition causes the second save to fail.
Closes #56
Adapt the ScriptTask behaivor to the behaivor of the ServiceTask
Please see #56 
> :bug: Fix Duplicate Call to ScriptTask#save() 

- package.json
- src/entity_type_services/node_instance.ts
- src/entity_types/boundary_event.ts
- src/entity_types/node_instance.ts
- src/entity_types/parallel_gateway.ts
- src/entity_types/process_token.ts
This updates token splitting according to these rules:
- Wenn ein BoundaryEvent ausgelöst wird, erstellt er sich einen Klon des
aktuellen Tokens
- An einen Parallel Split Gateway wird für jeden ausgehenden Flow ein Klon des
aktuellen Tokens erstellt
- An einem Parallel Join Gateway wird ein neuer Token erstellt, dessen history
sich aus den Histories aller Tokens zusammensetzt
- Freistehende Events ohne eingehenden Flow (Alle StartEvents und Intermediate
Catching Events (siehe BPMN Spech 2.0 Seite 261)) Erstellen einen komplett
neuen Token wenn sie ausgelöst werden
run diagrams with parallel gateways and boundary events, and see if the correct tokens follow the correct flows
> ✨ Improve token splitting

- package.json
- src/entity_types/end_event.ts
- src/entity_types/node_instance.ts
- src/entity_types/process.ts
Closes #63 
Requires: https://github.com/process-engine/process_engine_contracts/pull/21
Provide the key of a reached EndEvent through the regular messagebus channel, instead via a separate message.
See referenced issue for more details.
Easiest way to test this, is to use the integrationtests of the consumer api.
> Provide endEventkey with regular process.end notification

- package.json
- src/entity_type_services/process_def.ts
- src/entity_types/process_def.ts
Closes #68 
Closes #69
- Removed any and all remaining references pertaining to the "latest" and "draft" flags
- They are no longer a part of the `ProcessDefEntity` and will therefore no longer be included in the database, when a migration or database reset is performed
- All usages of these properties have been removed from the `ProcessDefEntityTypeService`
- Added the `isExecutable` Flag to the `ProcessDefEntity` and implemented the retrieval of this flag
- Fixed a ton of TSLint errors.
`Draft` and `latest` weren't used anywhere anymore and the `isExecutable` is only a descriptive flag that doesn't really do anything yet and is only required by the consumer API.
Therefore, these changes shouldn't really affect anything at all.
Even so, to keep older customer specific releases intact, …
> Add isExecutable Flag to ProcessDefEntity and remove all remaining "draft" and "latest" usages

- package.json
- src/entity_type_services/process_def.ts
- src/process_engine_service.ts
The name of a process definition can now be set by user when importing.
Related to:
- https://github.com/process-engine/bpmn-studio/pull/294
- https://github.com/process-engine/process_engine_http/pull/11
- https://github.com/process-engine/process_engine_contracts/pull/27
Needs to be published first:
- https://github.com/process-engine/process_engine_contracts/pull/27
- Import a XML with a custom name
> ✨ Add Select Own Process Definition Name

- package.json
- src/entity_types/process.ts
Adds the property `correlationId` to the process instance entity.
This requirement came during the implementation of the consumer api for the call activity.
> Add correlationId to ProcessInstanceEntity

- package.json
- src/process_engine_service.ts
Closes: #91 
Removes the `start` method from the `ProcessEngineService`.
This method was an attempt to duplicate the `execute` method. However, since it completely circumvented messagebus subscription, processes that were started this way were never finished.
Since it is best-practice  to use one of the `execute` methods anyway, the `start` method was removed.
This should only be an internal change, so backend-wise all should run as before.
For the bpmn studio, this fixes the following issue: https://github.com/process-engine/process_engine/issues/91
> Remove processEngineService.start convenience method

- package.json
- src/entity_types/node_instance.ts
This fixes the handling of node instance errors, by adding an additional flag `isEndedWithError`.
If set to true, the signal is given to end the process. 
If not, execution will continue.
Note:
I know, this is quick, dirty and ugly. But since this code is pretty much obsolete anyway, I think it would be pointless to invest a lot of time in this.
Best way is to run the integration tests.
> Check if a node instance was ended with an error before calling 'end'

- src/new_model/runtime/engine/handler/script_task_handler.ts
- src/new_model/runtime/engine/handler/service_task_handler.ts
- src/new_model/runtime/engine/handler/sub_process_handler.ts
- src/new_model/runtime/engine/handler/user_task_handler.ts
This PR ensures that the results of task calls are not only set on the `ProcessTokenFacade`, but also on the reference to the actual new `token.payload`.
It also adds checks to prevent the result from being `undefined`, because that let to the `tokenPayload` property being filtered in HTTP responses.
> Fix token payloads

- ioc_module.new-object-model.js
Deleted trailing comma in function call.
No issue, because this is a very quick fix.
Caused this error:
```
/Users/leonhardtobisch/bpmn/example_processes/solutions/Bookstore/node_modules/@process-engine/process_engine/ioc_module.new-object-model.js:116
)
^
SyntaxError: Unexpected token )
```
> Delete trailing comma in function call

- src/runtime/persistence/process_model_service.ts
* added an xml validation that 
* throws `UnprocessableEntityError` if an error is thrown during xml parsing
* throws `BadRequestError` if the parsed definitions don't contain a process whose `id` matches the name used to persist the xml definitions
See https://github.com/process-engine/skeleton/pull/71.
> Add XML Validation on Deployment

- package.json
- src/runtime/engine/handler/script_task_handler.ts
- src/runtime/persistence/flow_node_instance_service.ts
Depends on:
* https://github.com/process-engine/process_engine_contracts/pull/55
* https://github.com/process-engine/flow_node_instance.repository.sequelize/pull/7
* the script task handler now uses a try/catch for script execution
* if an error occurs during script execution, the new `persistOnError`-method is used to persist the state as `error`
* `persistOnError` has been implemented in `FlowNodeInstanceService`
See https://github.com/process-engine/process_engine_meta/pull/118.
> Add error persistance

- src/runtime/engine/handler/user_task_handler.ts
**Changes:**
1. Change the event name for finishing user tasks from `/processengine/node/:userTaskId/finish` to `/processengine/correlation/:correlationId/processinstance/:processInstanceId/node/:userTaskId/finish` to avoid event collison, when multiple user tasks have the same id
2. Add missing EventSubscription disposal
**Issues:**
Closes #159 
PR: #160
Follow the Steps described here:
https://github.com/process-engine/process_engine_runtime/issues/25
Finishing a specific user task should no longer result in other user tasks being finished aswell.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your …
> 🐛 Fix usertask event subscription

- package.json
- src/runtime/engine/handler/parallel_gateway_handler.ts
**Changes:**
1. Change `ParallelSplitGateway` state to 'finished', before the parallel branches get executed
2. Use the corresponding `ParallelJoinGateway` as the next flow node to run, instead of the FlowNode that follows the Join Gateway.
**Issues:**
Closes #171
PR: #172
- Run a process that uses ParallelGateways
- Best use parallel running branches with at least one UserTask
- When the parallel branches get run, the status of the ParallelSplitGateway should be `finished`
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix …
> 🐛 Persist parallel split gateway before branch executions

- package.json
- src/model/parser/process_lane_set_parser.ts
**Changes:**
Parsing a ProcessModel with an empty lane resulted in an internal error.
With this PR, such lanes will be parsed as empty instead.
PR: #185 
Try importing a ProcessModel with an empty lane.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> 🐛 Fix parsing of ProcessModels with empty lanes

- package.json
- src/runtime/engine/flow_node_handler/exclusive_gateway_handler.ts
**Changes:**
Perform a `persistOnError` for an ExclusiveSplitGateway, if one of its precondition fails.
PR: #210
Try running ExclusiveGateways that have no outgoing SequenceFlows with truthy conditions, or too many. The gateway will be persists as having been finished with errors.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> 🐛 Fix exclusive gateway error persistence

- package.json
- src/runtime/engine/flow_node_handler/parallel_gateway_handlers/parallel_join_gateway_handler.ts
- src/runtime/engine/flow_node_handler/parallel_gateway_handlers/parallel_split_gateway_handler.ts
**Changes:**
1. Refrain from using `Object.assign` when merging token results for a ParallelGateway.
- This fixes an issue where the ProcessTokenFacades contents would get wiped upon leaving the ParallelJoinGateway.
3. Add missing result tokens for ParallelJoinGateway. 
**Issues:**
Relates to https://github.com/process-engine/process_engine_runtime/issues/180
PR: #217
Use any process with parallel gateways and see that the tokens no longer get wiped. Using `token.current` and `token.history` is now possible again.
<details>
<summary>
</summary>
<br>
Example 1:
<pre> …
> 🐛 Fix token for parallel gateways

- package.json
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/flow_node_handler/boundary_event_handlers/error_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/boundary_event_handlers/message_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/boundary_event_handlers/signal_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/boundary_event_handlers/timer_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/call_activity_handler.ts
- src/runtime/engine/flow_node_handler/service_task_handlers/internal_service_task_handler.ts
- src/runtime/engine/flow_node_handler/sub_process_handler.ts
**Changes:**
1. Publish `ProcessInstanceFinished` notification whenever a `ProcessInstance` ends.
2. Await all FlowNodeInterruptions to allow the handlers to cleanup properly.
3. Await all `onError` state transitions to avoid timing issues.
4. Remove duplicated `onError` state transition from internal `ServiceTasks`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/188
PR: #228
State transitions and interruptions should now be handled properly.
Run some tests, using BoundaryEvents.
> ✨ Add sequelize transactions

- package.json
- src/runtime/persistence/process_model_service.ts
**Changes:**
Fixes an issue where requesting a ProcessModel that contains either an empty laneSet or no laneSets at all resulted in a 403 error.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/215
PR: #233
Try deploying and then retrieving a ProcessModel that has either an empty lane set or no lane set at all.
> 🐛 Fix claim checks on empty lane sets

- package.json
- src/runtime/persistence/process_model_service.ts
**Changes:**
1. Add more validations for ProcessModel deployment
- ProcessDefinitions must only contain one ProcessModel (Multiple ProcessModels are not supported right now)
- A ProcessModels ID must match the provided name under which the definition is to be stored (See linked issue).
2. Add some error logging to the `ProcessModelService`
3. Remove unnecessary Bluebird import from `ProcessModelService` (Bluebird Promises are now used by default).
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/219
PR: #234
Try importing ProcessModels that violate the restrictions described above.
> ✨ Add validations for ProcessModel persistence

- src/model/parser/event_parser.ts
- src/runtime/persistence/process_model_service.ts
**Changes:**
1. Adds a timer validation which validates, if the user passed the `TimerDefinition` in the right format/syntax
2. Throw a 400 Error if the user tries to upload a ProcessDefinitions, which contains a cyclic timer definition, since we currently don't support these.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/195
PR: #226
> ✨ Add a Timer Validation

- package.json
- src/runtime/engine/flow_node_handler/service_task_handlers/external_service_task_handler.ts
**Changes:**
Fix the error handling for misconfigured ExternalTak payloads, by making use of explicit Promise-rejection.
We need to do this explicitly, because otherwise the rejection would get swallowed up.
This would make the ProcessEngine appear to have frozen.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/216
PR: #235
- Try executing an ExternalTask that attempts to use a non-existent ProcessToken property as a payload.
- The resulting error should now be handled and returned correctly.
> 🐛 Fix ExternalTask payload evaluation

- ioc_module.js
- package.json
- src/runtime/engine/resume_process_serivce.ts
**Changes:**
Refactor `ResumeProcessService`:
1. Remove Unused Import.
2. Add CorrelationService and ModelParser.
3. Fix Bug Where The Wrong processModel was used to resume a process.
4. Refactor Query for active FlowNodeInstances when resuming a ProcessInstance.
5. Remove ProcessModelService.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/208
PR: #236 
> 🐛Fix Resuming Processes

- package.json
- src/runtime/persistence/process_model_service.ts
**Requires:**
https://github.com/process-engine/process_engine_contracts/pull/103
**Changes:**
Add missing `getByHash` method to `ProcessModelService`.
PR: #242
Use the service to query ProcessModels by their hash.
> 🐛 Expose get by hash on process model service

- src/model/parser/event_parser.ts
- test/bpmns/process_engine_io_release.bpmn
- test/runtime/engine/process_model_facade.spec.ts
**Changes:**
1. Allow Cyclic `TimerStartEvents` on a ProcessModel, if it contains at least one `StartEvent` without such a timer.
**Issues:**
Closes #240 
Related: https://github.com/process-engine/process_engine_runtime/issues/237
PR: #241 
Try deploying a ProcessModel with a cyclic TimerStartEvent and at least one other type of StartEvent.
> ✨Do not Throw an Error when a Process Contains a Cyclic TimerStartEvent and a Normal StartEvent

- package.json
- src/model/parser/event_parser.ts
- src/runtime/engine/flow_node_handler/boundary_event_handlers/timer_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts
- src/runtime/engine/timer_facade.ts
**Changes:**
1. Remove all timer expression validation from the ModelParser.
- Doing this during Model-parsing had the unfortunate side effect of preventing the use of token-expressions.
2. Implement timer validation in the TimerFacade.
3. Move all token expression functions from the FlowNodeHandlers to the TimerFacade
- This way, token expression parsing and timer validation gets executed for all timers on all FlowNodeHandlers that use them.
4. Fix an `Unhandled Promise rejection` issue with the `IntermediateTimerEvent` handler, which could occur when an error was thrown from within the TimerFacade.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/249
PR: #245
Deploying a ProcessModel with a timer that uses token-based expressions should be possible …
> 🐛 Fix timer expression parsing

- ioc_module.js
- package.json
- src/runtime/auto_start_service.ts
- src/runtime/execute_process_service.ts
- src/runtime/flow_node_handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts
- src/runtime/flow_node_handler/intermediate_event_handlers/intermediate_signal_catch_event_handler.ts
- src/runtime/flow_node_handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts
**Changes:**
1. Add `IdentityService` to `ExecuteProcessService` dependencies.
2. The `ExecuteProcessService` no longer expects full ProcessModels, but only ProcessModelIds for its `start` methods.
- The `ExecuteProcessService` will use our internal identity to retrieve full ProcessModels prior to execution
- This removes the need for external services to do that themselves and guarantees that the `ExecuteProcessService` has all relevent infos at hand.
- Note that claim checks and other security operations will already have been performed before hand by the Consumer API.
3. Remove the internal identity and the `IdentityService` from the `AutoStartService`.
- It no longer has to query full ProcessModels, so it doesn't need that identity any more.
- The service now only passes each …
> ♻️ Refactor expected parameters for process execution

- src/model/parser/event_parser.ts
- src/runtime/flow_node_handler/manual_task_handler.ts
- src/runtime/flow_node_handler/user_task_handler.ts
**Changes:**
1. Fix an issue which caused ManualTasks and UserTasks to be suspended before they had created their subscriptions on the EventAggregator.
- This could lead to situations, where a UserTaskHandler missed a `FinishUserTask` notification and remained suspended indefinitely.
2. Add validation for a UserTask's FormField expressions, to ensure a FormField doesn't attempt to use non-existing token values.
3. Fix ErrorEventDefinition parsing.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/240
Part of https://github.com/process-engine/process_engine_runtime/issues/263
PR: #251
Try executing a UserTask with a FormField, which tries accesing non-existing token values (like `${token.a.b.c.whatever}`).
Please check the boxes in this list after …
> 🔒 ♻️ Validate UserTask payloads

- package.json
- src/runtime/execute_process_service.ts
- src/runtime/resume_process_serivce.ts
**Changes:**
Account for the ProcessInstanceId when attempting to finish something within a Correlation.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/274
PR: #252
Finishing a ProcessInstance in a Correlation will now work properly.
> 🐛 Fix finishing of ProcessInstances in correlations

- ioc_module.js
- package.json
- src/runtime/flow_node_handler/call_activity_handler.ts
**Changes:**
CallActivities are no longer run through the ConsumerAPI, but directly through the ExecuteProcessService.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/277
PR: #254
This is an internal refactoring, so everything should run as before.
Maybe a little faster, now that we don't have to run all the way through the Consumer API to run CallActivities.
> ♻️ Use ExecuteProcessService to run CallActivities

- ioc_module.js
- package.json
- src/runtime/execute_process_service.ts
- src/runtime/flow_node_handler/call_activity_handler.ts
- src/runtime/flow_node_handler/end_event_handler.ts
- src/runtime/resume_process_serivce.ts
**Changes:**
1. Provide the FlowNodeId with messages send by EndEvents.
2. Include `EndEventId` and `EndEventName` in each CallActivity result token.
3. Provide FlowNodeInstanceId with `ProcessInstanceFinished` notifications
4. Add missing notifications to the `ResumeProcess` workflow
5. Ensure that the `ResumeProcessService` always returns the final result for each ProcessInstance it resumes.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/280
PR: #255
Use the new messages to send notifications for EndEvents.
> ✨ Add EndEvent name and ID to CallActivity result

- src/runtime/flow_node_handler/sub_process_handler.ts
**Changes:**
Fix a typo in the SubprocessHandler, which prevent the correct resumption of Subprocesses.
PR: #261
Fun fact: The linter doesn't complain about that typo. Explains why it went undetected.
- Start a ProcessModel that uses Subprocesses (ideally with a suspendable task, so you'll be able to follow its progress9
- Now forcibly stop the ProcessEngine
- Restart the ProcessEngine
- The Subprocess will be resumed from the point it was interrupted
> 🐛  Fix Subprocess Resumption

- src/runtime/flow_node_handler/service_task_handlers/external_service_task_handler.ts
**Changes:**
1. Add a missing `persistOnError` call to the external ServiceTask handler.
2. Fix Promise-rejection in external ServiceTask resumption.
3. Update token payload prior to `persistOnError` call.
PR: #267 
- Start a process that uses a ServiceTask with an "external" configuration
- Use a worker to finish that ExternalTask with an error
- The ServiceTask that uses this ExternalTask should now be finished with an error as well.
> 🐛 Add missing persistOnError call to external ServiceTask handler

- package.json
- src/runtime/flow_node_handler/service_task_handlers/external_service_task_handler.ts
**Changes:**
Only use an error's code and message for the external ServiceTask's `persistOnError` token, for easier usability.
The FlowNodeInstance already gets the full error, so there's no need to duplicate things.
Besides, stuff like call-stacks are technical information anyway and shouldn't be part of the token.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/309
PR: #268
When an ExternalTask is finished with an error, the corresponding ServiceTask gets the errors message and code as token payload.
The full error is stored with the FlowNodeInstance itself.
> 🐛 Fix error deserialization

- package.json
- src/runtime/facades/process_instance_state_handling_facade.ts
- src/runtime/flow_node_handler/call_activity_handler.ts
- src/runtime/resume_process_serivce.ts
**Changes:**
Rename property `processModels` to `processInstances` on Correlation-Model.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/311
PR: #269
This is an internal refactoring, so all should work as before.
> ♻️💄 Fix naming inconsistencies

- src/runtime/facades/timer_facade.ts
- src/runtime/flow_node_handler/event_handler/intermediate_timer_catch_event_handler.ts
- src/runtime/flow_node_handler/event_handler/start_event_handler.ts
1. Add missing `onError` state persistence to `IntermediateTimerCatchEvents`
2. Add interruption support to `StartEvent` handler; ProcessInstances that get stuck at a TimerStartEvent can now be stopped
- This is achieved by cancelling the Promise that contains the handlers execution.
3. Prevent the use of past dates with Date-type timer events
4. Throw an error when attempting to use cyclic timers with TimerStartEvents; these are not supported yet
5. Add verbose logging to the TimerFacade
Part of https://github.com/process-engine/process_engine_runtime/issues/330
PR: #272
Best use BPMN Studio for this.
- Start a ProcessInstance that starts with a TimerStartEvent
- An error will be thrown, if a cyclic timer, or a past date is used
- Try stopping the the ProcessInstance
- The …
> 🐛 Fix timer start event handling

- src/runtime/facades/timer_facade.ts
- src/runtime/flow_node_handler/boundary_event_handler/timer_boundary_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_timer_catch_event_handler.ts
- src/runtime/flow_node_handler/event_handler/start_event_handler.ts
1. Immediately start TimerEvents that use a date-type timer with a past date as value.
2. Robustify timer disposal for each handler that uses them. 
Part of https://github.com/process-engine/process_engine_runtime/issues/337
PR: #274
See [here](https://github.com/process-engine/process_engine_runtime/pull/339).
> ✨ Trigger TimerEvents with past date values immediately

- package.json
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/sub_process_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/flow_node_handler.ts
- src/runtime/flow_node_handler/gateway_handler/exclusive_gateway_handler.ts
- src/runtime/flow_node_handler/gateway_handler/gateway_handler.ts
- src/runtime/resume_process_serivce.ts
1. Fix FlowNodeInstance resumption:
- The function will no longer determine the FlowNodeInstance to resume by itself. This has proven ineffective, when dealing with a FlowNode that was executed multiple times within a single ProcessInstance.
-  Each FlowNodeHandler's resume function will now expect the matching FlowNodeInstance to be passed as a parameter.
- After the handler has finished, it will determine the next FlowNodes, as well as all matching FlowNodeInstances to resume. 
2. Fix ExclusiveGateway path resolving during resumption
- Resuming the gateway did not account for default SequenceFlows. This is fixed now.
3. Remove some duplicated ProcessToken creations that occurred during FlowNodeHandler resumption.
Part of https://github.com/process-engine/process_engine_runtime/issues/332 …
> 🐛 Fix resumption of FlowNodes with multiple FlowNodeInstances

- src/runtime/facades/process_token_facade.ts
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/flow_node_handler.ts
- src/runtime/flow_node_handler/gateway_handler/gateway_handler.ts
- src/runtime/flow_node_handler/gateway_handler/parallel_join_gateway_handler.ts
1. Refactor `ParallelJoinGatewayHandler` so that it stores all its `previousFlowNodeInstanceIds`.
2. Move some commonly used functionality to the base `FlowNodeHandler` to improve readability and maintainability.
3. Account for multiple `previousFlowNodeInstanceIds` in the base FlowNodeHandlers during Process resumption.
4. Fix an issue where the content of the `ProcessTokenFacade` would get wiped whenever a FlowNodeInstance was resumed.
5. Fix an issue that caused multiple instances for the same ParallelJoinGateway to be created during the resumption of multiple parallel running branches.
Part of https://github.com/process-engine/process_engine_runtime/issues/245
PR: #276
Resuming a ProcessInstance that got interrupted while executing parallel branches should now be possible.
> 🐛 Store all previousFlowNodeInstanceIds for ParallelJoinGateways

- package.json
- src/runtime/flow_node_handler/activity_handler/service_task_handlers/external_service_task_handler.ts
1. Allow ExternalTask topics to contain token expressions
2. Remove some useless code docs 
3. Move ExternalTask topic- and payload parsing to main `createExternalTask` function
Part of https://github.com/process-engine/process_engine_runtime/issues/347
PR: #279
- Create a ProcessModel with an ExternalTask that has a token expression as a topic (i.e. `token.history.someFlowNodeId.someReference`)
- Create an ExternalTask Worker that listens for the matching topic
- Run that ProcessModel
- Make sure you pass the correct topic as an initial payload!
- See that the ExternalTask uses the correct topic and gets processed as expected
> ✨ External task topics from token expression

- Jenkinsfile
- package.json
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/call_activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/empty_activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/manual_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/receive_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/script_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/send_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/service_task_handlers/external_service_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/service_task_handlers/internal_service_task_handler.ts
- src/runtime/flow_node_handler/activity_handler/sub_process_handler.ts
- src/runtime/flow_node_handler/activity_handler/user_task_handler.ts
1. Add `publishActivityReachedNotification` and `publishActivityFinishedNotification` to the base ActivityHandler
2. Use these generic notification functions in the CallActivityHandler
3. Add these notifications to all remaining non-interactive ActivityHandlers (ScriptTask, ServiceTask, SendTask, ReceiveTask and Subprocess)
4. Refactor handlers EmptyActivities, UserTasks and ManualTasks to use the updated message types and notification naming schemas.
- They will still follow their current notification pattern though, since it deviates from the pattern implemented in the base handler.
5. Only run `npm ci` during Jenkins builds, when building the develop or master branches.
Part of https://github.com/process-engine/process_engine_runtime/issues/349
PR: #278
> ✨Additional notifications for activities

- src/runtime/flow_node_handler/activity_handler/service_task_handlers/external_service_task_handler.ts
1. Parsing ExternalTask topics and token payloads is now the first thing the handler does.
- This allows the handler to detect configuration errors before anything actually happens.
- It also fixes the referenced issue, where an ExternalTasks token expression was put into the created metrics, instead of the parsed payload.
2. Renamed the parser functions for topics and payloads to something more fitting.
Part of https://github.com/process-engine/process_engine_runtime/issues/352
PR: #281
- Run a ProcessModel that uses ExternalTasks
- After the ExternalTask was run, examine the generated metrics for the ProcessModel
- See that ExternalTask's actual payload is put with the metrics, instead of the configured token expression
> ♻️ Move ExternalTask expression parsing to top of the handler

- package-lock.json
- package.json
- src/runtime/cronjob_service.ts
1. Implement `getActive` UseCase for `CronjobService`
Part of https://github.com/process-engine/process_engine_runtime/issues/363
PR: #283
- Deploy some ProcessModels with cyclic `TimerStartEvents`
- Start the CronjobService
- Access `getActive` and see that a list with all cronjobs is returned
> ✨Add getActiveCronjobs UseCase

- package.json
- src/runtime/execute_process_service.ts
- src/runtime/flow_node_handler/activity_handler/receive_task_handler.ts
1. Fix reference error in ReceiveTaskHandler's `persistOnExit` call
2. Remove duplicated initial token payload assignment
Part of https://github.com/process-engine/process_engine_runtime/issues/471
PR: #310
- Start a Process that uses a `SendTask` and `ReceiveTask`
- Don't attach any payloads to either task
- Start the process instance without any initial payload
- See that the message received by the `ReceiveTask` will have no payload
- See that the `ReceiveTask` is still able to change its state to `finished`
> 🐛 Fix ReceiveTask state transition to "finished"

- Jenkinsfile
- package.json
- src/runtime/execute_process_service.ts
- src/runtime/facades/process_instance_state_handling_facade.ts
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/flow_node_handler.ts
1. Attach a users identity to termination errors, if the Process was terminated by a user
2. Pass the terminating users identity to the CorrelationService, so claim checks will be performed against that identity instead
3. Log the name of the user that terminates a ProcessInstance
Part of https://github.com/process-engine/process_engine_runtime/issues/474
PR: #311
- Start a ProcessInstance
- Send a termination signal for that ProcessInstance, using a different identity as payload (Or use the `terminateProcessInstance` function of the Management API)
- See that all claim checks are performed against the identity that made the termination request
> 🔒 Use correct identity for terminating ProcessInstances manually

- package.json
- src/runtime/resume_process_serivce.ts
1. Check for orphaned ProcessInstances during initial ProcessInstance resumption
2. When dealing with terminated or errored ProcessInstances, use whichever FlowNode contains corresponding state as a baseline
- Note that the result for `terminated` FlowNodes will always be the same, so it doesn't matter which of these FlowNodes is used
- If the FlowNodeInstance has no error attached, a fallback error is used (this was possible in older versions, for which we must account here)
Part of https://github.com/process-engine/process_engine_runtime/issues/486
PR: #315
- Run any kind of ProcessInstance and let it finish with varying results (success, ProcessTermination, or with an unhandled error on one of the FlowNodes)
- Manually set the state of the corresponding ProcessInstance to "running" …
>  ✨ Clear orphaned ProcessInstances on startup

- package.json
- src/runtime/facades/timer_facade.ts
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/call_activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/service_task_handlers/external_service_task_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/error_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/message_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/signal_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/timer_boundary_event_handler.ts
- src/runtime/resume_process_serivce.ts
1. Detach BoundaryEvents prior to running `afterExecute` cleanup on decorated Activities
2. Implement resumption for BoundaryEventHandlers
3. When resuming a decorated activity, all attached BoundaryEvents will now be resumed, instead of executed
- This fixes the issue with multiple `onEnter` tokens for a single BoundaryEvent
4. Fix some reference issues
5. Unsubscribe from `ExternalTaskFinished` event, when an `ExternalServiceTaskHandler` gets interruped
6. Fix finishing of BoundaryEvents
- Each BoundaryEvent should now always produce an `onExit` token, either when trigger, or when the activity finishes and removes its BoundaryEvents
7. Refine resumption of ProcessInstances. A ProcessInstance is now considered to be orphaned, if it:
- is in a running state
- has no active …
> 🐛 Fix BoundaryEvent state transitions

- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/flow_node_handler.ts
- src/runtime/flow_node_handler/gateway_handler/gateway_handler.ts
- src/runtime/flow_node_handler/gateway_handler/parallel_join_gateway_handler.ts
1. Remove event subscriptions from ParallelJoinGatewayHandler, after it finished or was interrupted
- This fixes the following: https://github.com/process-engine/process_engine_runtime/issues/517
2. Add `persistOnSuspend` and `persistOnResume` to base `FlowNodeHandler`
2. Reduce complexity of ActivityHandler
- Remove `persistOnSuspend` and `persistOnResume`
- Remove interrupt wrapper
- Remove `subscribeToProcessTermination` override and use base function from `FlowNodeHandler` instead
3. Add `subscribeToProcessError` to base `FlowNodeHandler`
4. Make all FlowNodeHandlers subscribe to ProcessInstance errors
5. When a ProcessInstance gets interrupted by an unhandled error (i.e. an error that is not intercepted through a BoundaryEvent or an error thrown by an ErrorEndEvent), all …
> ♻️ Refactor Event Subscription handling

- package.json
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/gateway_handler/gateway_handler.ts
1. GatewayHandlers now wrap their `execute` hooks into an async lock. 
- This is done to prevent race conditions during Join Gateway execution (See references issue).
2. Remove timeout used as workaround from base handlers 
Part of https://github.com/process-engine/process_engine_runtime/issues/523
PR: #322
- Create a process that makes use of ParallelGateways - ideally with 3+ branches
- Best use tasks that can be finished simultaneously for each branch (like ExternalServiceTasks with the same topic)
-  Run that process 4-5 times
- When all ExternalTasks have been created, start a Worker that can process these tasks simultaenously
- Note that all FlowNodes of each ProcessInstance will be finished correctly
> ♻️ Add async locks for gateways

- src/model/parser/flow_node_parsers/event_parser.ts
1. Intercept errors when parsing Signal/Message event definitions (like missing `signalRef` or `messageRef` properties on the raw event definition)
2. Do not produce 429 errors when encountering such errors, but instead print a warning that the event will not be executable
- Usually this should throw an error. However, since the parser is also used when _retrieving_ ProcessModels, this would break all `getProcessModel` UseCase for the ConsumerAPI and ManagementAPI
- This would leave the user with no way of retrieving - and consequently fixing - a ProcessModel that has such an invalid event attached to it
- Instead, the FlowNodeHandlers will produce errors, when attempting to execute such an invalid event.
3. Move event validation error production to dedicated function
4. Use generic type …
> ﻿﻿♻️ Intercept and handle event parsing errors

- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/error_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/message_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/signal_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/timer_boundary_event_handler.ts
1. Fix creation of FlowNodeHandlers for FlowNodeInstances that followed a triggered BoundaryEvent
2. Fix null-value issue with `previousFlowNodeInstanceId` on BoundaryEventInstances
3. Robustify discovery of FlowNodeInstances that followed a triggered BoundaryEvent (improved early exit)
4. Use Bluebird.map instead of Promise.map to avoid reference errors, in case Bluebird is not the default Promise library of the hosting application
Part of https://github.com/process-engine/process_engine_runtime/issues/544
PR: #326
See the reproduction steps described in the issue.
> 🐛 Fix resumption of activities that followed a triggered BoundaryEvent

- src/runtime/flow_node_handler/activity_handler/call_activity_handler.ts
1. Fix wrong subscription path for the processEndSubscription
PR: #331
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> 🐛 Fix the wrong subscription message path
