process-engine/process_engine_core

- src/entity_types/node_instance.ts
The behavior of cancelling tasks is changed.
Former behavior: If a task is cancelled (mostly by boundary events) the task follows the cancel boundary event if any AND the regular flow of the task.
New behavior: If a task is cancelled the task follows ONLY the cancel boundary event if any AND NOT the regular flow of the task.
> cancel flow on cancelled tasks

- src/entity_types/user_task.ts
- src/process_engine_service.ts
I added a method to get the userTaskData of a userTask.
This closes #9 
This requires https://github.com/process-engine/process_engine_contracts/pull/4 to be merged.
Other related PRs: https://github.com/process-engine/process_engine_http/pull/2
Use the new method and see, if you get an Object of type `IUserTaskMessageData`
> ✨  finish getUserTaskData

- src/entity_type_services/process_def.ts
I added the interfaces necessary to allow for starting a process by its id, not only by its key.
This requires https://github.com/process-engine/process_engine_contracts/pull/5 to be merged
Where before you could only start a process with a `/start`-body like this:
```JSON
{
"msg": {
"key": "start"
}
}
```
you can now also do this:
```JSON
{
"msg": {
"id": "facd924b-eb4c-4b50-82c6-41519cbb62d8"
}
}
```
> ✨  add process-start-by-id

- src/entity_types/end_event.ts
- src/entity_types/user_task.ts
This PR handles the issue https://github.com/process-engine/process_engine/issues/14.
start a demo and start a process with a lane without role configured. A user task should be shown for either a guest or a user logged in.
> publish to flattened roles

- src/process_engine_service.ts
See issue https://github.com/process-engine/process_engine/issues/21
> change overwrite to true

- ioc_module.js
- package.json
- src/entity_type_services/process_def.ts
- src/entity_types/process.ts
- src/entity_types/process_def.ts
- src/process_engine_service.ts
this is my take on #18 
This is tested over multiple instances and using the browser
When this is merged, the code of this package can be cleaned up quite a bit as described in [this document](https://docs.google.com/document/d/14dm1rsbp9lo3MGKDWk_IZkrwKjCfil1QCi2rIHf4lLE) (see "Positive Nebeneffekte")
run the post-route described in #18 and see that the process is executed and you get the last token-data as response as soon as the process is finished
> ✨ implement sync process execution

- package.json
- src/entity_type_services/process_def.ts
- src/entity_types/process.ts
- src/entity_types/process_def.ts
This branch refactors the versioning with draft and latest.
Theese things changed:
- getDraft() won't create a draft
- getLatest() and getDraft() will throw errors if nothing is found
- publishDraft() creates a copy of the model and makes it the new latest
- importBpmnFromXml() now imports processes as drafts before publishing them
This requires https://github.com/process-engine/process_engine_contracts/pull/15 to be merged
Use Postman to check if my statements above are true.
> ♻️ Add Versioning

- package.json
:arrow_up: Upgrade @process-engine/process_engine_contracts to 1.0.0-rc5
checkout & install
> ⬆️ :arrow_up: Upgrade @process-engine/process_engine_contracts to 1.0.0-rc5

- src/entity_types/node_instance.ts
This fixes issue https://github.com/process-engine/process_engine/issues/32
check out branch 'feature/add_test_loop' of 'process_engine_meta' and execute 'npm test'. The test 'Process-Engine POST -> /processengine/execute test_loop' should succeed.
> History Array in Process Token is not filled correctly

- src/new_model/model/parser/activity_parser.ts
- src/new_model/model/parser/event_parser.ts
- src/new_model/model/parser/flow_node_parser.ts
- src/new_model/model/parser/process_parser.ts
- src/new_model/runtime/engine/handler/end_event_handler.ts
This PR implements handler to handle a ErrorEndEvent.
Related PR: https://github.com/process-engine/process_engine_contracts/pull/36
* Create a process with an ErrorEndEvent
* Execute the Process
* There is an issue concerning an error boundary event in conjunction with a call activity that ends with an error end event.
> Implement Handlers for the ErrorEndEvent

- src/model/parser/activity_parser.ts
This PR fixes the parsing of the preferredControl.
- Test this PR: https://github.com/process-engine/bpmn-studio/pull/779
> 🐛 Fix Activity Parser for PreferredControl

- PULL_REQUEST_TEMPLATE.md
- package.json
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/handler/call_activity_handler.ts
- src/runtime/engine/handler/end_event_handler.ts
- src/runtime/engine/handler/exclusive_gateway_handler.ts
- src/runtime/engine/handler/intermediate_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_message_throw_event_handler.ts
- src/runtime/engine/handler/intermediate_throw_event_handler.ts
- src/runtime/engine/handler/parallel_gateway_handler.ts
- src/runtime/engine/handler/script_task_handler.ts
- src/runtime/engine/handler/service_task_handler.ts
- src/runtime/engine/handler/start_event_handler.ts
- src/runtime/engine/handler/sub_process_handler.ts
- src/runtime/engine/handler/user_task_handler.ts
- src/runtime/persistence/correlation_service.ts
- src/runtime/persistence/flow_node_instance_service.ts
Requires: 
https://github.com/process-engine/process_engine_contracts/pull/62
https://github.com/process-engine/flow_node_instance.repository.sequelize/pull/10
Part of the Heatmap feature.
- Remove `ExecutionContextFacade` parameter from the FlowNodeInstanceRepository interface
- Reorder the methods on that interface so that they are grouped together in a meaningful way
- Also change their signatures so that each state-changing method uses the same type of signature
- Suspend and Resume are no longer treated as a flag, but as an actual FlowNodeState
- FlowNodeInstances will no longer have only a single process token that gets updated every time its state changes
- The type of the token will be defined through the use of the enumeration `ProcessTokenType`
- Instead, each state change will …
> ♻️ Store Enter and Exit Token Separately

- package.json
- src/model/parser/process_lane_set_parser.ts
**Changes:**
This fixes an issue where Process Lanes with only a single activity will cause the model parser to crash.
Try parsing a process model that contains a lane with only a single activity.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR …
>  🐛 Fix lane parsing if only one activity is present

- package.json
- src/runtime/engine/handler/call_activity_handler.ts
**Changes:**
This fixes an issue, where a call activity will not get the correlation id of the parent process.
This resulted in broken correlations and made it impossible to resume sub processes, which had waiting user tasks.
**Issues:**
https://github.com/process-engine/bpmn-studio/issues/876
PR: #153
Use a process with a call activity, which calls a subprocess with a user task.
- Start the process
- Wait until the user task in the subprocess is reached and suspended
- Use the Management- or Consumer- APIs `getUserTasksForCorrelation` function to get a list of waiting user tasks for the matching correlation
- The result should list your user task(s)
<details>
<summary>
:warning: Before merging please click here to expand and …
> 🐛 Pass correlation id to call activity

- package.json
- src/model/parser/activity_parser.ts
- src/model/type_factory.ts
- src/runtime/engine/handler/service_task_handler.ts
**Changes:**
1. Fixes an issue, where ServiceTasks would not return the required `NextFlowNodeInfo`, if anyhing other than a method invocation is used, or if no invocation at all is present.
2. Adds a filter to the ModelParser, which filters out empty `camunda:property` tags from the parsed xml code.
**Issues:**
Closes https://github.com/process-engine/process_engine_runtime/issues/24
PR: #158
Execute a process model with empty service tasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
>  🐛 Fix service task continuation

- package.json
- src/runtime/persistence/correlation_service.ts
**Changes:**
1. Include suspended FlowNodeInstances in getActiveCorrelation result
PR: #161
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre> …
> 🐛 Include suspended processes in active correlation list

- ioc_module.js
- package.json
- src/runtime/engine/handler/intermediate_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/index.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_throw_event_handler.ts
- src/runtime/engine/handler/timer_boundary_event_handler.ts
**Changes:**
1. Implement Handler for `IntermediateTimerCatchEvent`
2. Fix the handling of cycle-timers with the `TimerBoundaryEvent`
**Issues:**
Closes #162 
PR: #163
Run a process that uses an IntermediateTimerEvent
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> ✨Add Intermediate timer events

- ioc_module.js
- package.json
- src/model/type_factory.ts
- src/runtime/engine/execute_process_service.ts
- src/runtime/persistence/correlation_service.ts
- src/runtime/persistence/process_model_service.ts
**Changes:**
Implements all interface changes as described here:
https://github.com/process-engine/process_engine_contracts/pull/64
1. Add some code documentation
2. Some Stylefixes, like reordering imports, refactoring functions, etc.
3. Remove unnecessary usages of `ExecutionContextFacade` and use `IIdentity` instead, where necessary
4. Enhance `CorrelationService`
- Add `createEntry` - Create a new correlation in the database
- Add `getByCorrelationId` - Retrieve a correlation and its process model hash by the given correlation id
- Include suspended and running FlowNodeInstances, when querying active correlations
5. Rename `ProcessDefinitionRaw` to `ProcessDefinitionFromRepository` and move it to the `Runtime.Types` namespace
6. Enhance `ExecuteProcessService`:
- Add …
> ✨ Get process definitions by correlation

- package.json
- test/bpmns/DemoNutztierRiss.bpmn
- test/runtime/engine/process_model_facade.spec.ts
- test/runtime/engine/process_model_facade_test_fixture.ts
:tada: **Thanks for submitting this Pull Request**
---
**Changes:**
1. :white_check_mark: Unit-Tests for ProcessModelFacade added
PR: #156 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> ProcessModelFacadeTest added

- ioc_module.js
- package.json
- src/model/parser/event_parser.ts
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/handler/end_event_handler.ts
- src/runtime/engine/handler/index.ts
- src/runtime/engine/handler/intermediate_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/index.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_message_throw_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_signal_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_signal_throw_event_handler.ts
- src/runtime/engine/handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts
- src/runtime/engine/handler/intermediate_throw_event_handler.ts
- src/runtime/engine/handler/message_boundary_event_handler.ts
- src/runtime/engine/handler/signal_boundary_event_handler.ts
- src/runtime/engine/handler/start_event_handler.ts
- src/runtime/engine/handler/sub_process_handler.ts
- src/runtime/engine/handler/timer_boundary_event_handler.ts
- src/runtime/engine/index.ts
- src/runtime/engine/timer_facade.ts
Follow-up PR to: #175
Closes: #175
**Changes:**
1. Implement Signals and Messages for Intermediate-, Boundary, Start- and End- Events
2. Refactor the handlers for Start- and End- Events so that they can effectively handle each of the different event types
3. Move handling of internal timers to a new `TimerFacade`, which can be used by StartEvents, BoundaryEvents and IntermediateEvents
4. Always parse EventDefinitions when parsing events with the model parser
5. Refactor the event name that gets published to the EventAggregator, when a normal EndEvent is reached. The previous version only included the FlowNodeID, which could lead to event collisions. The new event name also includes the correlationId and the processModelId
6. Remove the `processInstanceId` constraint from the existing …
> ✨ Additional intermediate and boundary events

- package.json
- src/runtime/engine/flow_node_handler/service_task_handler.ts
**Changes:**
1. add identity to external task
PR: #182 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR …
> :sparkles: add identity to external task

- src/runtime/engine/flow_node_handler/service_task_handler.ts
**Changes:**
1. ✨ publish event when ExternalTask created
PR: #183 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> :sparkles: add longpolling for external tasks

- package.json
- src/model/parser/activity_parser.ts
- src/runtime/engine/flow_node_handler/service_task_handler.ts
**Changes:**
1. :sparkles: use payload from ServiceTask if defined
PR: #184 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> :sparkles: add payload for ExternalTask

- package.json
- src/model/parser/activity_parser.ts
- src/model/parser/event_parser.ts
- src/model/parser/flow_node_parser.ts
- src/model/parser/process_parser.ts
- src/model/type_factory.ts
- src/runtime/engine/flow_node_handler/end_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_throw_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_signal_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_signal_throw_event_handler.ts
- src/runtime/engine/flow_node_handler/message_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/signal_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/start_event_handler.ts
**Changes:**
1. Remove unnecessary "reference" wrappers from signals, errors and messages
2. Parse complete messages and signals to use with SignalEvents and MessageEvents, so we can get a message's/signal's name.
3. Use a signal's or message's name, instead of its ID, for subscribing to the corresponging events.
PR: #186
Subscribe to a message or signal by its name.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this …
> ♻️ Use name of signals and messages

- package.json
- src/runtime/persistence/process_model_service.ts
**Changes:**
1. Adds a suitable method to check if a child lane set is empty.
**Issues:**
Relates to: https://github.com/process-engine/bpmn-studio/issues/946
PR: #189
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
> 🐛Fix Child Lane Set Filter

- package.json
- src/runtime/persistence/process_model_service.ts
**Changes:**
1. Fix the ChildLaneSet Filter if the lane is inaccessible.
**Issues:**
Relates to: process-engine/bpmn-studio#946
PR: #192
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> 🐛Fix ChildLaneSet Filter

- src/runtime/persistence/process_model_service.ts
**Changes:**
1. Fix a bug in the access check of lanes.
**Issues:**
Relates to: process-engine/bpmn-studio#946
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
> 🐛Fix Access Check

- package.json
- src/runtime/engine/flow_node_handler/flow_node_handler.ts
- src/runtime/engine/flow_node_handler/parallel_gateway_handler.ts
- src/runtime/engine/flow_node_handler/sub_process_handler.ts
- src/runtime/persistence/flow_node_instance_service.ts
**Changes:**
1. Adjust the paramters on the persist methods.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/133
PR: #198
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
> ✨Use new Parameters on Persist Methods

- README.md
**Changes:**
Rewrite the Readme so that it no longer reads like the description of a PoC, but an actual description of the package.
PR: #194
Read it.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary> …
> 📖  Rewrite the Readme

- package.json
- src/runtime/engine/process_model_facade.ts
**Changes:**
1. Updates the `process_engine_contracts` version.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/112
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> ✨Adjust Version of Contracts

- package.json
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/flow_node_handler/call_activity_handler.ts
- src/runtime/engine/flow_node_handler/end_event_handler.ts
- src/runtime/engine/flow_node_handler/error_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/exclusive_gateway_handler.ts
- src/runtime/engine/flow_node_handler/flow_node_handler.ts
- src/runtime/engine/flow_node_handler/flow_node_handler_factory.ts
- src/runtime/engine/flow_node_handler/intermediate_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_throw_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_signal_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_signal_throw_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts
- src/runtime/engine/flow_node_handler/intermediate_throw_event_handler.ts
- src/runtime/engine/flow_node_handler/message_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/parallel_gateway_handler.ts
- src/runtime/engine/flow_node_handler/receive_task_handler.ts
- src/runtime/engine/flow_node_handler/script_task_handler.ts
- src/runtime/engine/flow_node_handler/send_task_handler.ts
- src/runtime/engine/flow_node_handler/service_task_handler.ts
- src/runtime/engine/flow_node_handler/signal_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/start_event_handler.ts
- src/runtime/engine/flow_node_handler/sub_process_handler.ts
- src/runtime/engine/flow_node_handler/timer_boundary_event_handler.ts
- src/runtime/engine/flow_node_handler/user_task_handler.ts
- src/runtime/persistence/flow_node_instance_service.ts
**Changes:**
1. Add `previousFlowNodeInstanceId` to the `persistOnEnter` logic for the `FlowNodeInstanceService`.
2. Add `previousFlowNodeInstanceId` to the `execute` method of the `IFlowNodeHandler` to make it accessible for each FlowNodeHandler.
* This allows each FlowNodeInstance to get information about the FNI that was executed previously
3. Remove the `flowNode` property from the `IFlowNodeHandler.execute` method and instead use it as a class-property on the `FlowNodeHandler` base class
* This avoids having to toss around the FlowNode through each and every class method of the FlowNodeHandler. That never made much sense to begin with.
* To make it easier to use each FlowNode within its specific handler, the handler can get it through a private wrapper property, whose name reflects …
> ✨ Add "previousFlowNodeInstanceId" to FlowNodeHandlers

- src/runtime/engine/flow_node_handler/flow_node_handler.ts
- src/runtime/engine/flow_node_handler/parallel_gateway_handler.ts
- src/runtime/engine/process_token_facade.ts
**Changes:**
1. Fix token merging of parallel gateway
2. Fix setting FlowNodeInstanceId in token
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/152
PR: #209
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1135**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
> 🐛 Fix Token Merging of Parallel Gateway

- ioc_module.js
- package.json
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/process_model_facade.ts
- src/runtime/persistence/correlation_service.ts
- src/runtime/persistence/flow_node_instance_service.ts
**Changes:**
1. Add new query functions to the `FlowNodeInstanceService` and `CorrelationService` to make complex UseCases easier to query.
2. Fix the CorrelationService's grouping of ProcessModels by their Correlation. 
3. Include the `ParentProcessInstanceId` in a Correlation-Entry that describes a subprocess.
PR: #211
Use the new Services to query Correlations and FlowNodeInstances.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the …
> ✨ Add UseCase specific queries to persistence layer

- package.json
- src/runtime/engine/execute_process_service.ts
- src/runtime/engine/flow_node_handler/sub_process_handler.ts
- src/runtime/engine/process_token_facade.ts
**Changes:**
1. The handler for Subprocesses now assigns custom ProcessInstanceIds and a callerId to its subprocess.
2. Change return type of `executeProcessService._createProcessInstanceConfig` to appropiate type.
This is a prerequisite for resuming Subprocesses, because the handler must be able to retrieve all FlowNodeInstances that belong to its subprocess.
PR: #214
Execute a Subprocess and see that its FlowNodeInstances now have a custom ProcessInstanceId and get the handlers instance ID assigned as their "callerId".
<details>
<summary>
</summary>
<br>
Example 1: …
> ♻️ Add Caller ID and Custom Process Instance ID to Subprocess

- package.json
- src/runtime/engine/flow_node_handler/call_activity_handler.ts
**Changes:**
Refactor the `CallActivityHandler` to use the new namespaces from the `ConsumerApiContracts` package.
PR: #230
This only changes some type imports, so all should run as before.
> ♻️ 💄 Refactor Namespaces and API interfaces

- ioc_module.js
- package.json
- src/runtime/engine/flow_node_handler/call_activity_handler.ts
- src/runtime/engine/resume_process_serivce.ts
- src/runtime/persistence/correlation_service.ts
- src/runtime/persistence/delete_process_model_service.ts
**Changes:**
1. Add IamService to IoC
2. Update Contracts
3. Add IamService And Claim Checks
4. Add Filter by Identity Methods
5. Add Identity to Params
**Issues:**
Closes #https://github.com/process-engine/process_engine_runtime/issues/225
PR: #237 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy …
> ✨Add Identity to Correlation Service

- package.json
- src/model/parser/activity_parser.ts
**Changes:**
Fix an issue where empty values in a UserTask's enum-type FormField caused the Model-Parser to crash.
PR: #243
Try parsing a ProcessModel that contains a UserTask with an enum-type FormField without any values.
> 🐛 Fix user task form field enum value parsing

- package.json
- src/runtime/flow_node_handler/flow_node_handler.ts
**Changes:**
1. Fix an issue, where multiple branches in a parallel gateway were not truly run in parallel to each other.
2. Shorten some documentation on the `FlowNodeInstanceHandler` to avoid linter complaints about too many lines for the file.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/265
PR: #249
See [this issue](https://github.com/process-engine/process_engine_runtime/issues/265) for details.
> 🐛 Fix parallelization of ProcessInstance branches

- src/runtime/execute_process_service.ts
- src/runtime/flow_node_handler/flow_node_handler_interruptible.ts
- src/runtime/resume_process_serivce.ts
**Changes:**
1. Add `TerminateProcessInstance` functionality.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/199
PR: #257
Run the tests.
> ✨Make Processes Interruptible

- test/bpmns/diagram_with_invalid_task_configs.bpmn
- test/bpmns/intermediate_event_link_test.bpmn
- test/bpmns/process_with_boundary_events.bpmn
- test/bpmns/user_task_multiple.bpmn
- test/bpmns/user_task_test.bpmn
- test/process_model_facade/get_boundary_events_for.spec.ts
- test/process_model_facade/get_end_events.spec.ts
- test/process_model_facade/get_flow_node_by_id.spec.ts
- test/process_model_facade/get_incoming_sequence_flows_for.spec.ts
- test/process_model_facade/get_is_executable.spec.ts
- test/process_model_facade/get_link_catch_events_by_link_name.spec.ts
- test/process_model_facade/get_next_flow_nodes_for.spec.ts
- test/process_model_facade/get_outgoing_sequence_flows_for.spec.ts
- test/process_model_facade/get_previous_flow_nodes_for.spec.ts
- test/process_model_facade/get_sequence_flow_between.spec.ts
- test/process_model_facade/get_single_start_event.spec.ts
- test/process_model_facade/get_start_event_by_id.spec.ts
- test/process_model_facade/get_start_events.spec.ts
- test/process_model_facade/get_user_tasks.spec.ts
**Changes:**
Add full UnitTest coverage for the ProcessModelFacade, making it the very first backend component to have UnitTest coverage.
PR: #258
Run the tests.
> ✅ Add UnitTests for ProcessModelFacade

- package.json
**Changes:**
1. Update mocha to v6
2. Use `ts-mocha` instead of `ts-node`
- `ts-mocha` is actually a lot faster than `ts-node`.
3. Move mocha from dependencies to devDependencies.
PR: #259
Run the tests.
> ⬆️ Update mocha to v6

- src/runtime/flow_node_handler/service_task_handlers/external_service_task_handler.ts
**Changes:**
Finish ExternalTasks with an error, when the corresponding ProcessInstance is interrupted.
PR: #264
- Start a ProcessInstance with an external ServiceTask
- Wait until that task is reached and suspended
- Stop the ProcessInstance
- The ExternalTask now gets finished with an error and is no longer available for external workers
> ♻️ Abort ExternalTasks when a Process is interrupted

- src/runtime/flow_node_handler/service_task_handlers/external_service_task_handler.ts
**Changes:**
Fix an issue that prevented external ServiceTasks from being interrupted correctly.
PR: #265
Aborting external ServiceTasks should no longer produce errors.
> 🐛 Fix interruption of external ServiceTasks

- ioc_module.js
- package.json
- src/runtime/flow_node_handler/activity_handler/activity_handler.ts
- src/runtime/flow_node_handler/activity_handler/call_activity_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/error_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/message_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/signal_boundary_event_handler.ts
- src/runtime/flow_node_handler/boundary_event_handler/timer_boundary_event_handler.ts
- src/runtime/flow_node_handler/event_handler/event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_empty_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_link_catch_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_link_throw_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_message_catch_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_message_throw_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_signal_catch_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_signal_throw_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_timer_catch_event_handler.ts
**Changes:**
1. Add Events for Call Activities
2. Add Events for Boundary Events
3. Add Events for Intermediate Events
PR: #273
> Related to https://github.com/process-engine/process_engine_runtime/pull/334
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1412**
> ✨ Add Events for Call Activities, Boundary Events and Intermediate Events

- ioc_module.js
- package-lock.json
- package.json
- src/runtime/cronjob_service.ts
1. Add `CronjobHistoryService` to `CronjobService`
2. Persist each execution of a cronjob through the `CronjobHistoryService`
Part of https://github.com/process-engine/process_engine_runtime/issues/365
PR: #284
> ✨Persist cronjob history

- test/flow_node_persistence_facade/persist_on_enter.spec.ts
- test/flow_node_persistence_facade/persist_on_error.spec.ts
- test/flow_node_persistence_facade/persist_on_exit.spec.ts
- test/flow_node_persistence_facade/persist_on_resume.spec.ts
- test/flow_node_persistence_facade/persist_on_suspend.spec.ts
- test/flow_node_persistence_facade/persist_on_terminate.spec.ts
- test/mocks/flow_node_instance_service_mock.ts
- test/mocks/index.ts
- test/mocks/logging_service_mock.ts
- test/mocks/metrics_service_mock.ts
- test/test_fixture_provider.ts
Add unit tests for FlowNodePersistenceFacade.
PR: #286
Run the tests.
> ✅ Unit tests for FlowNodePersistenceFacade

- src/runtime/flow_node_handler/gateway_handler/parallel_join_gateway_handler.ts
1. Fix Join Gateway Finish Check
Related to https://github.com/process-engine/process_engine_runtime/issues/389
PR: #295
> 🐛 Fix Join Gateway Finish Check

- ioc_module.js
- package.json
- src/runtime/cronjob_service.ts
1. Publish events if a cronjob has been executed, created, stopped, updated or removed.
PR: #296 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> ✨Publish cronjob events

- src/runtime/flow_node_handler/gateway_handler/parallel_join_gateway_handler.ts
1. Fix Changing ParallelJoinGateway State on Error
Related to https://github.com/process-engine/process_engine_runtime/issues/459
PR: #307
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/464**
> 🐛 Fix Changing ParallelJoinGateway State on Error

- src/runtime/resume_process_serivce.ts
1. Resume ProcessInstances by ProcessInstanceState Instead of FlowNodeStates
Related to https://github.com/process-engine/process_engine_runtime/issues/458
PR: #308
-**Have a look at https://github.com/process-engine/process_engine_runtime/pull/465**
> 🐛Resume ProcessInstances by ProcessInstanceState Instead of FlowNodeStates

- package.json
- src/runtime/facades/timer_facade.ts
- src/runtime/flow_node_handler/boundary_event_handler/timer_boundary_event_handler.ts
- src/runtime/flow_node_handler/event_handler/intermediate_timer_catch_event_handler.ts
1. Fix Resuming Timer Events
Related to https://github.com/process-engine/process_engine_runtime/issues/549
PR: #329
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/554**
> 🐛 Fix Resuming Timer Events

- src/runtime/flow_node_handler/activity_handler/call_activity_handler.ts
- src/runtime/flow_node_handler/flow_node_handler.ts
1. Fix the call activity interruption bug
PR: #330 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> 🐛Fix call activity interruption
